//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyndicateServiceLibWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmemberbank
    {
        public int MMashatId { get; set; }
        public int DofatSarfId { get; set; }
        public double summony { get; set; }
        public Nullable<System.DateTime> sendbankdate { get; set; }
        public Nullable<double> amanatmony { get; set; }
        public Nullable<System.DateTime> amanatwareddate { get; set; }
        public long AutoId { get; set; }
    }
}
